import { Product } from "@/lib/types";
import {
  Apple,
  CreditCard,
  LayoutDashboard,
  Logs,
  Package,
  Settings,
  ShoppingBasket,
  Truck,
  UsersRound,
} from "lucide-react";

export const sidebarItems = [
  {
    label: "Dashboard",
    icon: <LayoutDashboard />,
    href: "/",
  },
  {
    label: "Products",
    icon: <Apple />,
    href: "/products",
  },
  {
    label: "Categories",
    icon: <Logs />,
    href: "/categories",
  },
  {
    label: "Customers",
    icon: <UsersRound />,
    href: "/customers",
  },
  {
    label: "Delivery Boys",
    icon: <Package />,
    href: "/delivery",
  },
  {
    label: "Orders",
    icon: <ShoppingBasket />,
    href: "/orders",
  },
  {
    label: "Shipments",
    icon: <Truck />,
    href: "/shipments",
  },
  {
    label: "Transactions",
    icon: <CreditCard />,
    href: "/transactions",
  },
  {
    label: "Settings",
    icon: <Settings />,
    href: "/settings",
  },
];

export const products: Product[] = [
  {
    id: "1",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "2",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "3",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "4",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "5",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "6",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "7",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "8",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
  {
    id: "9",
    title: "Lorem Ipsum",
    category: "Battery",
    price: 110.4,
    image: "/images/card-image-",
    summary: "Lorem ipsum is placeholder text commonly used in the graphic.",
    sales: 1269,
    remainingProducts: 1269,
  },
];
